Add files via upload
Currently, the Bayes optimization will run into an error...
that code will be fixed later...

Initial distance: 1427
Final distance: 560
Initial distance: 3300
Final distance: 804
Initial distance: 4440
Final distance: 947
Initial distance: 1529
Final distance: 567
Initial distance: 1737
Final distance: 608
Initial distance: 3556
Final distance: 979
Initial distance: 4319
Final distance: 992
Initial distance: 1715
Final distance: 587
Initial distance: 3122
Final distance: 899
Initial distance: 1718
Final distance: 605
Initial distance: 4554
Final distance: 1105
Initial distance: 4363
Error: Population is empty
Traceback (most recent call last):

  File "/home/blinky/.local/lib/python3.10/site-packages/spyder_kernels/py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "/home/blinky/Documents/Programming/TSP_GA_V17_LKH_bayes_optimization.py", line 404, in <module>
    result = gp_minimize(objective_function, space, n_calls=20)

  File "/home/blinky/.local/lib/python3.10/site-packages/skopt/optimizer/gp.py", line 281, in gp_minimize
    return base_minimize(

  File "/home/blinky/.local/lib/python3.10/site-packages/skopt/optimizer/base.py", line 332, in base_minimize
    next_y = func(next_x)

  File "/home/blinky/Documents/Programming/TSP_GA_V17_LKH_bayes_optimization.py", line 391, in objective_function
    return -calculate_route_length(best_route, create_distance_matrix(num_cities))

  File "/home/blinky/Documents/Programming/TSP_GA_V17_LKH_bayes_optimization.py", line 226, in calculate_route_length
    if route_np is None or len(route_np) == 0:

TypeError: len() of unsized object